---
- name: get trigram
  hosts: all
  gather_facts: false
  tasks:
    - name: Get scm_revision details
      debug:
        msg: "{{ tower_project_revision }}"
      register: revision_info
    
    - name: Job id
      debug:
        msg: "{{ tower_job_id }}"

    - name: Job name
      debug:
        msg: "{{ tower_job_template_name }}"



        
